 
import numpy as np
import datetime
import h5py
import os
 
# Note this example script was generated by nxdl_to_hdf5.py using the current 
# installed version of the NEXUS definitions ver[v2020.10] 
 
root = h5py.File('h5py_NXmonopd.h5', 'w')
 
root.create_group('entry')
root['/entry'].attrs['NX_class'] = 'NXentry'
root['/entry'].attrs['EX_required'] = 'true'
 
root['/entry/'].create_group('untitled_instrument')
root['/entry/untitled_instrument'].attrs['NX_class'] = 'NXinstrument'
root['/entry/untitled_instrument'].attrs['EX_required'] = 'true'
 
root['/entry/untitled_instrument/'].create_group('untitled_source')
root['/entry/untitled_instrument/untitled_source'].attrs['NX_class'] = 'NXsource'
root['/entry/untitled_instrument/untitled_source'].attrs['EX_required'] = 'true'
 
root['/entry/untitled_instrument/'].create_group('untitled_crystal')
root['/entry/untitled_instrument/untitled_crystal'].attrs['NX_class'] = 'NXcrystal'
root['/entry/untitled_instrument/untitled_crystal'].attrs['EX_required'] = 'true'
 
root['/entry/untitled_instrument/'].create_group('untitled_detector')
root['/entry/untitled_instrument/untitled_detector'].attrs['NX_class'] = 'NXdetector'
root['/entry/untitled_instrument/untitled_detector'].attrs['EX_required'] = 'true'
 
root['/entry/'].create_group('untitled_sample')
root['/entry/untitled_sample'].attrs['NX_class'] = 'NXsample'
root['/entry/untitled_sample'].attrs['EX_required'] = 'true'
 
root['/entry/'].create_group('untitled_monitor')
root['/entry/untitled_monitor'].attrs['NX_class'] = 'NXmonitor'
root['/entry/untitled_monitor'].attrs['EX_required'] = 'true'
 
root['/entry/'].create_group('untitled_data')
root['/entry/untitled_data'].attrs['NX_class'] = 'NXdata'
root['/entry/untitled_data'].attrs['EX_required'] = 'true'
 
root['/entry'].create_dataset(name='title', data=1.0, maxshape=None)
root['/entry/title'].attrs['type'] = 'NX_FLOAT'
root['/entry/title'].attrs['EX_required'] = 'true'
 
root['/entry'].create_dataset(name='start_time', data='2021-03-22T16:42:15.684223', maxshape=None)
root['/entry/start_time'].attrs['type'] = 'NX_DATE_TIME'
root['/entry/start_time'].attrs['EX_required'] = 'true'
 
# Valid enumeration values for root['/entry']['definition'] are: 
#	 NXmonopd
 
root['/entry'].create_dataset(name='definition', data='NXmonopd', maxshape=None)
root['/entry/definition'].attrs['type'] = 'NX_DATE_TIME'
root['/entry/definition'].attrs['EX_required'] = 'true'
 
root['/entry/untitled_instrument/untitled_source'].create_dataset(name='type', data='2021-03-22T16:42:15.687270', maxshape=None)
root['/entry/untitled_instrument/untitled_source/type'].attrs['type'] = 'NX_DATE_TIME'
root['/entry/untitled_instrument/untitled_source/type'].attrs['EX_required'] = 'true'
 
root['/entry/untitled_instrument/untitled_source'].create_dataset(name='name', data='2021-03-22T16:42:15.688271', maxshape=None)
root['/entry/untitled_instrument/untitled_source/name'].attrs['type'] = 'NX_DATE_TIME'
root['/entry/untitled_instrument/untitled_source/name'].attrs['EX_required'] = 'true'
 
# Valid enumeration values for root['/entry/untitled_instrument/untitled_source']['probe'] are: 
#	 neutron
#	 x-ray
#	 electron
 
root['/entry/untitled_instrument/untitled_source'].create_dataset(name='probe', data='neutron', maxshape=None)
root['/entry/untitled_instrument/untitled_source/probe'].attrs['type'] = 'NX_DATE_TIME'
root['/entry/untitled_instrument/untitled_source/probe'].attrs['EX_required'] = 'true'
 
root['/entry/untitled_instrument/untitled_crystal'].create_dataset(name='wavelength', data=[1.], maxshape=None, compression="gzip")
root['/entry/untitled_instrument/untitled_crystal/wavelength'].attrs['type'] = 'NX_FLOAT'
root['/entry/untitled_instrument/untitled_crystal/wavelength'].attrs['EX_required'] = 'true'
root['/entry/untitled_instrument/untitled_crystal/wavelength'].attrs['units'] = 'NX_WAVELENGTH'
 
root['/entry/untitled_instrument/untitled_detector'].create_dataset(name='polar_angle', data=[1.], maxshape=None, compression="gzip")
root['/entry/untitled_instrument/untitled_detector/polar_angle'].attrs['type'] = 'NX_FLOAT'
root['/entry/untitled_instrument/untitled_detector/polar_angle'].attrs['EX_required'] = 'true'
root['/entry/untitled_instrument/untitled_detector/polar_angle'].attrs['axis'] = '1'
 
root['/entry/untitled_instrument/untitled_detector'].create_dataset(name='data', data=[1], maxshape=None)
root['/entry/untitled_instrument/untitled_detector/data'].attrs['type'] = 'NX_INT'
root['/entry/untitled_instrument/untitled_detector/data'].attrs['EX_required'] = 'true'
root['/entry/untitled_instrument/untitled_detector/data'].attrs['signal'] = '1'
 
root['/entry/untitled_sample'].create_dataset(name='name', data=1, maxshape=None)
root['/entry/untitled_sample/name'].attrs['type'] = 'NX_INT'
root['/entry/untitled_sample/name'].attrs['EX_required'] = 'true'
 
root['/entry/untitled_sample'].create_dataset(name='rotation_angle', data=1.0, maxshape=None)
root['/entry/untitled_sample/rotation_angle'].attrs['type'] = 'NX_FLOAT'
root['/entry/untitled_sample/rotation_angle'].attrs['EX_required'] = 'true'
root['/entry/untitled_sample/rotation_angle'].attrs['units'] = 'NX_ANGLE'
 
# Valid enumeration values for root['/entry/untitled_monitor']['mode'] are: 
#	 monitor
#	 timer
 
root['/entry/untitled_monitor'].create_dataset(name='mode', data='monitor', maxshape=None)
root['/entry/untitled_monitor/mode'].attrs['type'] = 'NX_FLOAT'
root['/entry/untitled_monitor/mode'].attrs['EX_required'] = 'true'
 
root['/entry/untitled_monitor'].create_dataset(name='preset', data=1.0, maxshape=None)
root['/entry/untitled_monitor/preset'].attrs['type'] = 'NX_FLOAT'
root['/entry/untitled_monitor/preset'].attrs['EX_required'] = 'true'
 
root['/entry/untitled_monitor'].create_dataset(name='integral', data=1.0, maxshape=None)
root['/entry/untitled_monitor/integral'].attrs['type'] = 'NX_FLOAT'
root['/entry/untitled_monitor/integral'].attrs['EX_required'] = 'true'
root['/entry/untitled_monitor/integral'].attrs['units'] = 'NX_ANY'
root['/entry/definition'].attrs['EX_doc'] = '     Official NeXus NXDL schema to which this file conforms    '
root['/entry/untitled_instrument/untitled_crystal/wavelength'].attrs['EX_doc'] = '       Optimum diffracted wavelength      '
root['/entry/untitled_instrument/untitled_detector/data'].attrs['EX_doc'] = '       detector signal (usually counts) are already                     corrected for detector efficiency      '
root['/entry/untitled_sample/name'].attrs['EX_doc'] = '      Descriptive name of sample     '
root['/entry/untitled_sample/rotation_angle'].attrs['EX_doc'] = '      Optional rotation angle for the case when the powder diagram                      has been obtained through an omega-2theta scan like from a                      traditional single detector powder diffractometer     '
root['/entry/untitled_monitor/mode'].attrs['EX_doc'] = '      Count to a preset value based on either clock time (timer)                      or received monitor counts (monitor).     '
root['/entry/untitled_monitor/preset'].attrs['EX_doc'] = '      preset value for time or monitor     '
root['/entry/untitled_monitor/integral'].attrs['EX_doc'] = '      Total integral monitor counts     '
root['/'].attrs['default'] = 'entry'
root['/entry'].attrs['default'] = 'untitled_data'
root.attrs['file_name'] = os.path.abspath('NXmonopd')
root.attrs['file_time'] = datetime.datetime.now().isoformat()
root.attrs['h5py_version'] = h5py.version.version
root.attrs['HDF5_Version'] = h5py.version.hdf5_version
root.close()


