 
import numpy as np
import datetime
import h5py
import os
 
# Note this example script was generated by nxdl_to_hdf5.py using the current 
# installed version of the NEXUS definitions ver[v2020.10] 
 
root = h5py.File('h5py_NXmx.h5', 'w')
 
root.create_group('entry')
root['/entry'].attrs['NX_class'] = 'NXentry'
root['/entry'].attrs['EX_required'] = 'true'
 
root['/entry/'].create_group('data')
root['/entry/data'].attrs['NX_class'] = 'NXdata'
root['/entry/data'].attrs['EX_required'] = 'true'
 
root['/entry/'].create_group('sample')
root['/entry/sample'].attrs['NX_class'] = 'NXsample'
root['/entry/sample'].attrs['EX_required'] = 'true'
 
root['/entry/sample/'].create_group('transformations')
root['/entry/sample/transformations'].attrs['NX_class'] = 'NXtransformations'
root['/entry/sample/transformations'].attrs['EX_required'] = 'false'
 
root['/entry/'].create_group('instrument')
root['/entry/instrument'].attrs['NX_class'] = 'NXinstrument'
root['/entry/instrument'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/'].create_group('attenuator')
root['/entry/instrument/attenuator'].attrs['NX_class'] = 'NXattenuator'
root['/entry/instrument/attenuator'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/'].create_group('NXdetector_group')
root['/entry/instrument/NXdetector_group'].attrs['NX_class'] = 'NXdetector_group'
root['/entry/instrument/NXdetector_group'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/'].create_group('detector')
root['/entry/instrument/detector'].attrs['NX_class'] = 'NXdetector'
root['/entry/instrument/detector'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/detector/'].create_group('transformations')
root['/entry/instrument/detector/transformations'].attrs['NX_class'] = 'NXtransformations'
root['/entry/instrument/detector/transformations'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/detector/'].create_group('collection')
root['/entry/instrument/detector/collection'].attrs['NX_class'] = 'NXcollection'
root['/entry/instrument/detector/collection'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/detector/'].create_group('NXdetector_module')
root['/entry/instrument/detector/NXdetector_module'].attrs['NX_class'] = 'NXdetector_module'
root['/entry/instrument/detector/NXdetector_module'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/'].create_group('beam')
root['/entry/instrument/beam'].attrs['NX_class'] = 'NXbeam'
root['/entry/instrument/beam'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/beam/'].create_group('incident_wavelength_spectrum')
root['/entry/instrument/beam/incident_wavelength_spectrum'].attrs['NX_class'] = 'NXdata'
root['/entry/instrument/beam/incident_wavelength_spectrum'].attrs['EX_required'] = 'false'
 
root['/entry/'].create_group('source')
root['/entry/source'].attrs['NX_class'] = 'NXsource'
root['/entry/source'].attrs['EX_required'] = 'true'
 
root['/entry'].create_dataset(name='title', data='SAMPLE-CHAR-DATA', maxshape=None)
root['/entry/title'].attrs['type'] = 'NX_CHAR'
root['/entry/title'].attrs['EX_required'] = 'false'
 
root['/entry'].create_dataset(name='start_time', data='2021-03-26T13:07:53.060290', maxshape=None)
root['/entry/start_time'].attrs['type'] = 'NX_DATE_TIME'
root['/entry/start_time'].attrs['EX_required'] = 'true'
 
root['/entry'].create_dataset(name='end_time', data='2021-03-26T13:07:53.063302', maxshape=None)
root['/entry/end_time'].attrs['type'] = 'NX_DATE_TIME'
root['/entry/end_time'].attrs['EX_required'] = 'false'
 
root['/entry'].create_dataset(name='end_time_estimated', data='2021-03-26T13:07:53.066303', maxshape=None)
root['/entry/end_time_estimated'].attrs['type'] = 'NX_DATE_TIME'
root['/entry/end_time_estimated'].attrs['EX_required'] = 'true'
 
# Valid enumeration values for root['/entry']['definition'] are: 
#	 NXmx
 
root['/entry'].create_dataset(name='definition', data='NXmx', maxshape=None)
root['/entry/definition'].attrs['type'] = 'NX_CHAR'
root['/entry/definition'].attrs['EX_required'] = 'true'
 
root['/entry/data'].create_dataset(name='data', data=1.0, maxshape=None)
root['/entry/data/data'].attrs['type'] = 'NX_NUMBER'
root['/entry/data/data'].attrs['EX_required'] = 'true'
 
root['/entry/sample'].create_dataset(name='name', data='SAMPLE-CHAR-DATA', maxshape=None)
root['/entry/sample/name'].attrs['type'] = 'NX_CHAR'
root['/entry/sample/name'].attrs['EX_required'] = 'true'
 
root['/entry/sample'].create_dataset(name='depends_on', data='SAMPLE-CHAR-DATA', maxshape=None)
root['/entry/sample/depends_on'].attrs['type'] = 'NX_CHAR'
root['/entry/sample/depends_on'].attrs['EX_required'] = 'true'
 
root['/entry/sample'].create_dataset(name='temperature', data=1.0, maxshape=None)
root['/entry/sample/temperature'].attrs['type'] = 'NX_NUMBER'
root['/entry/sample/temperature'].attrs['EX_required'] = 'false'
root['/entry/sample/temperature'].attrs['units'] = 'NX_TEMPERATURE'
 
root['/entry/instrument'].create_dataset(name='name', data='SAMPLE-CHAR-DATA', maxshape=None)
root['/entry/instrument/name'].attrs['type'] = 'NX_CHAR'
root['/entry/instrument/name'].attrs['EX_required'] = 'true'
 
root['/entry/instrument'].create_dataset(name='time_zone', data='2021-03-26T13:07:53.092283', maxshape=None)
root['/entry/instrument/time_zone'].attrs['type'] = 'NX_DATE_TIME'
root['/entry/instrument/time_zone'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/attenuator'].create_dataset(name='attenuator_transmission', data=1.0, maxshape=None)
root['/entry/instrument/attenuator/attenuator_transmission'].attrs['type'] = 'NX_NUMBER'
root['/entry/instrument/attenuator/attenuator_transmission'].attrs['EX_required'] = 'false'
root['/entry/instrument/attenuator/attenuator_transmission'].attrs['units'] = 'NX_UNITLESS'
 
root['/entry/instrument/NXdetector_group'].create_dataset(name='group_names', data='SAMPLE-CHAR-DATA', maxshape=None)
root['/entry/instrument/NXdetector_group/group_names'].attrs['type'] = 'NX_CHAR'
root['/entry/instrument/NXdetector_group/group_names'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/NXdetector_group'].create_dataset(name='group_index', data=1, maxshape=None)
root['/entry/instrument/NXdetector_group/group_index'].attrs['type'] = 'NX_INT'
root['/entry/instrument/NXdetector_group/group_index'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/NXdetector_group'].create_dataset(name='group_parent', data=1, maxshape=None)
root['/entry/instrument/NXdetector_group/group_parent'].attrs['type'] = 'NX_INT'
root['/entry/instrument/NXdetector_group/group_parent'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/detector'].create_dataset(name='depends_on', data='SAMPLE-CHAR-DATA', maxshape=None)
root['/entry/instrument/detector/depends_on'].attrs['type'] = 'NX_CHAR'
root['/entry/instrument/detector/depends_on'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/detector'].create_dataset(name='data', data=1.0, maxshape=None)
root['/entry/instrument/detector/data'].attrs['type'] = 'NX_NUMBER'
root['/entry/instrument/detector/data'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/detector'].create_dataset(name='description', data='SAMPLE-CHAR-DATA', maxshape=None)
root['/entry/instrument/detector/description'].attrs['type'] = 'NX_CHAR'
root['/entry/instrument/detector/description'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/detector'].create_dataset(name='time_per_channel', data='SAMPLE-CHAR-DATA', maxshape=None)
root['/entry/instrument/detector/time_per_channel'].attrs['type'] = 'NX_CHAR'
root['/entry/instrument/detector/time_per_channel'].attrs['units'] = 'NX_TIME'
root['/entry/instrument/detector/time_per_channel'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/detector/NXdetector_module'].create_dataset(name='data_origin', data=1, maxshape=None)
root['/entry/instrument/detector/NXdetector_module/data_origin'].attrs['type'] = 'NX_INT'
root['/entry/instrument/detector/NXdetector_module/data_origin'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/detector/NXdetector_module'].create_dataset(name='data_size', data=1, maxshape=None)
root['/entry/instrument/detector/NXdetector_module/data_size'].attrs['type'] = 'NX_INT'
root['/entry/instrument/detector/NXdetector_module/data_size'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/detector/NXdetector_module'].create_dataset(name='data_stride', data=1, maxshape=None)
root['/entry/instrument/detector/NXdetector_module/data_stride'].attrs['type'] = 'NX_INT'
root['/entry/instrument/detector/NXdetector_module/data_stride'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/detector/NXdetector_module'].create_dataset(name='module_offset', data=1.0, maxshape=None)
root['/entry/instrument/detector/NXdetector_module/module_offset'].attrs['type'] = 'NX_NUMBER'
root['/entry/instrument/detector/NXdetector_module/module_offset'].attrs['EX_required'] = 'false'
root['/entry/instrument/detector/NXdetector_module/module_offset'].attrs['units'] = 'NX_LENGTH'
 
root['/entry/instrument/detector/NXdetector_module'].create_dataset(name='fast_pixel_direction', data=1.0, maxshape=None)
root['/entry/instrument/detector/NXdetector_module/fast_pixel_direction'].attrs['type'] = 'NX_NUMBER'
root['/entry/instrument/detector/NXdetector_module/fast_pixel_direction'].attrs['EX_required'] = 'true'
root['/entry/instrument/detector/NXdetector_module/fast_pixel_direction'].attrs['units'] = 'NX_LENGTH'
 
root['/entry/instrument/detector/NXdetector_module'].create_dataset(name='slow_pixel_direction', data=1.0, maxshape=None)
root['/entry/instrument/detector/NXdetector_module/slow_pixel_direction'].attrs['type'] = 'NX_NUMBER'
root['/entry/instrument/detector/NXdetector_module/slow_pixel_direction'].attrs['EX_required'] = 'true'
root['/entry/instrument/detector/NXdetector_module/slow_pixel_direction'].attrs['units'] = 'NX_LENGTH'
 
root['/entry/instrument/detector'].create_dataset(name='distance', data=1.0, maxshape=None)
root['/entry/instrument/detector/distance'].attrs['type'] = 'NX_FLOAT'
root['/entry/instrument/detector/distance'].attrs['EX_required'] = 'true'
root['/entry/instrument/detector/distance'].attrs['units'] = 'NX_LENGTH'
 
root['/entry/instrument/detector'].create_dataset(name='distance_derived', data=np.int8(0), maxshape=None)
root['/entry/instrument/detector/distance_derived'].attrs['type'] = 'NX_BOOLEAN'
root['/entry/instrument/detector/distance_derived'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/detector'].create_dataset(name='dead_time', data=1.0, maxshape=None)
root['/entry/instrument/detector/dead_time'].attrs['type'] = 'NX_FLOAT'
root['/entry/instrument/detector/dead_time'].attrs['EX_required'] = 'false'
root['/entry/instrument/detector/dead_time'].attrs['units'] = 'NX_TIME'
 
root['/entry/instrument/detector'].create_dataset(name='count_time', data=1.0, maxshape=None)
root['/entry/instrument/detector/count_time'].attrs['type'] = 'NX_NUMBER'
root['/entry/instrument/detector/count_time'].attrs['EX_required'] = 'true'
root['/entry/instrument/detector/count_time'].attrs['units'] = 'NX_TIME'
 
root['/entry/instrument/detector'].create_dataset(name='beam_center_derived', data=np.int8(0), maxshape=None)
root['/entry/instrument/detector/beam_center_derived'].attrs['type'] = 'NX_BOOLEAN'
root['/entry/instrument/detector/beam_center_derived'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/detector'].create_dataset(name='beam_center_x', data=1.0, maxshape=None)
root['/entry/instrument/detector/beam_center_x'].attrs['type'] = 'NX_FLOAT'
root['/entry/instrument/detector/beam_center_x'].attrs['EX_required'] = 'true'
root['/entry/instrument/detector/beam_center_x'].attrs['units'] = 'NX_LENGTH'
 
root['/entry/instrument/detector'].create_dataset(name='beam_center_y', data=1.0, maxshape=None)
root['/entry/instrument/detector/beam_center_y'].attrs['type'] = 'NX_FLOAT'
root['/entry/instrument/detector/beam_center_y'].attrs['EX_required'] = 'true'
root['/entry/instrument/detector/beam_center_y'].attrs['units'] = 'NX_LENGTH'
 
root['/entry/instrument/detector'].create_dataset(name='angular_calibration_applied', data=np.int8(0), maxshape=None)
root['/entry/instrument/detector/angular_calibration_applied'].attrs['type'] = 'NX_BOOLEAN'
root['/entry/instrument/detector/angular_calibration_applied'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/detector'].create_dataset(name='angular_calibration', data=1.0, maxshape=None)
root['/entry/instrument/detector/angular_calibration'].attrs['type'] = 'NX_FLOAT'
root['/entry/instrument/detector/angular_calibration'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/detector'].create_dataset(name='flatfield_applied', data=np.int8(0), maxshape=None)
root['/entry/instrument/detector/flatfield_applied'].attrs['type'] = 'NX_BOOLEAN'
root['/entry/instrument/detector/flatfield_applied'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/detector'].create_dataset(name='flatfield', data=1.0, maxshape=None)
root['/entry/instrument/detector/flatfield'].attrs['type'] = 'NX_NUMBER'
root['/entry/instrument/detector/flatfield'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/detector'].create_dataset(name='flatfield_error', data=1.0, maxshape=None)
root['/entry/instrument/detector/flatfield_error'].attrs['type'] = 'NX_NUMBER'
root['/entry/instrument/detector/flatfield_error'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/detector'].create_dataset(name='flatfield_errors', data=1.0, maxshape=None)
root['/entry/instrument/detector/flatfield_errors'].attrs['type'] = 'NX_NUMBER'
root['/entry/instrument/detector/flatfield_errors'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/detector'].create_dataset(name='pixel_mask_applied', data=np.int8(0), maxshape=None)
root['/entry/instrument/detector/pixel_mask_applied'].attrs['type'] = 'NX_BOOLEAN'
root['/entry/instrument/detector/pixel_mask_applied'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/detector'].create_dataset(name='pixel_mask', data=1, maxshape=None)
root['/entry/instrument/detector/pixel_mask'].attrs['type'] = 'NX_INT'
root['/entry/instrument/detector/pixel_mask'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/detector'].create_dataset(name='countrate_correction_applied', data=np.int8(0), maxshape=None)
root['/entry/instrument/detector/countrate_correction_applied'].attrs['type'] = 'NX_BOOLEAN'
root['/entry/instrument/detector/countrate_correction_applied'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/detector'].create_dataset(name='bit_depth_readout', data=1, maxshape=None)
root['/entry/instrument/detector/bit_depth_readout'].attrs['type'] = 'NX_INT'
root['/entry/instrument/detector/bit_depth_readout'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/detector'].create_dataset(name='detector_readout_time', data=1.0, maxshape=None)
root['/entry/instrument/detector/detector_readout_time'].attrs['type'] = 'NX_FLOAT'
root['/entry/instrument/detector/detector_readout_time'].attrs['EX_required'] = 'false'
root['/entry/instrument/detector/detector_readout_time'].attrs['units'] = 'NX_TIME'
 
root['/entry/instrument/detector'].create_dataset(name='frame_time', data=1.0, maxshape=None)
root['/entry/instrument/detector/frame_time'].attrs['type'] = 'NX_FLOAT'
root['/entry/instrument/detector/frame_time'].attrs['EX_required'] = 'false'
root['/entry/instrument/detector/frame_time'].attrs['units'] = 'NX_TIME'
 
root['/entry/instrument/detector'].create_dataset(name='gain_setting', data='SAMPLE-CHAR-DATA', maxshape=None)
root['/entry/instrument/detector/gain_setting'].attrs['type'] = 'NX_CHAR'
root['/entry/instrument/detector/gain_setting'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/detector'].create_dataset(name='saturation_value', data=1, maxshape=None)
root['/entry/instrument/detector/saturation_value'].attrs['type'] = 'NX_INT'
root['/entry/instrument/detector/saturation_value'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/detector'].create_dataset(name='underload_value', data=1, maxshape=None)
root['/entry/instrument/detector/underload_value'].attrs['type'] = 'NX_INT'
root['/entry/instrument/detector/underload_value'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/detector'].create_dataset(name='sensor_material', data='SAMPLE-CHAR-DATA', maxshape=None)
root['/entry/instrument/detector/sensor_material'].attrs['type'] = 'NX_CHAR'
root['/entry/instrument/detector/sensor_material'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/detector'].create_dataset(name='sensor_thickness', data=1.0, maxshape=None)
root['/entry/instrument/detector/sensor_thickness'].attrs['type'] = 'NX_FLOAT'
root['/entry/instrument/detector/sensor_thickness'].attrs['EX_required'] = 'true'
root['/entry/instrument/detector/sensor_thickness'].attrs['units'] = 'NX_LENGTH'
 
root['/entry/instrument/detector'].create_dataset(name='threshold_energy', data=1.0, maxshape=None)
root['/entry/instrument/detector/threshold_energy'].attrs['type'] = 'NX_FLOAT'
root['/entry/instrument/detector/threshold_energy'].attrs['EX_required'] = 'false'
root['/entry/instrument/detector/threshold_energy'].attrs['units'] = 'NX_ENERGY'
 
root['/entry/instrument/detector'].create_dataset(name='type', data='SAMPLE-CHAR-DATA', maxshape=None)
root['/entry/instrument/detector/type'].attrs['type'] = 'NX_CHAR'
root['/entry/instrument/detector/type'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/beam'].create_dataset(name='incident_wavelength', data=1.0, maxshape=None)
root['/entry/instrument/beam/incident_wavelength'].attrs['type'] = 'NX_FLOAT'
root['/entry/instrument/beam/incident_wavelength'].attrs['EX_required'] = 'true'
root['/entry/instrument/beam/incident_wavelength'].attrs['units'] = 'NX_WAVELENGTH'
 
root['/entry/instrument/beam'].create_dataset(name='incident_wavelength_weight', data=1.0, maxshape=None)
root['/entry/instrument/beam/incident_wavelength_weight'].attrs['type'] = 'NX_FLOAT'
root['/entry/instrument/beam/incident_wavelength_weight'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/beam'].create_dataset(name='incident_wavelength_weights', data=1.0, maxshape=None)
root['/entry/instrument/beam/incident_wavelength_weights'].attrs['type'] = 'NX_FLOAT'
root['/entry/instrument/beam/incident_wavelength_weights'].attrs['EX_required'] = 'false'
 
root['/entry/instrument/beam'].create_dataset(name='incident_wavelength_spread', data=1.0, maxshape=None)
root['/entry/instrument/beam/incident_wavelength_spread'].attrs['type'] = 'NX_FLOAT'
root['/entry/instrument/beam/incident_wavelength_spread'].attrs['EX_required'] = 'false'
root['/entry/instrument/beam/incident_wavelength_spread'].attrs['units'] = 'NX_WAVELENGTH'
 
root['/entry/instrument/beam'].create_dataset(name='flux', data=1.0, maxshape=None)
root['/entry/instrument/beam/flux'].attrs['type'] = 'NX_FLOAT'
root['/entry/instrument/beam/flux'].attrs['EX_required'] = 'false'
root['/entry/instrument/beam/flux'].attrs['units'] = 'NX_FLUX'
 
root['/entry/instrument/beam'].create_dataset(name='total_flux', data=1.0, maxshape=None)
root['/entry/instrument/beam/total_flux'].attrs['type'] = 'NX_FLOAT'
root['/entry/instrument/beam/total_flux'].attrs['EX_required'] = 'true'
root['/entry/instrument/beam/total_flux'].attrs['units'] = 'NX_FREQUENCY'
 
root['/entry/instrument/beam'].create_dataset(name='incident_beam_size', data=1.0, maxshape=None)
root['/entry/instrument/beam/incident_beam_size'].attrs['type'] = 'NX_FLOAT'
root['/entry/instrument/beam/incident_beam_size'].attrs['EX_required'] = 'true'
root['/entry/instrument/beam/incident_beam_size'].attrs['units'] = 'NX_LENGTH'
 
# Valid enumeration values for root['/entry/instrument/beam']['profile'] are: 
#	 Gaussian
#	 Airy
#	 top-hat
#	 rectangular
 
root['/entry/instrument/beam'].create_dataset(name='profile', data='Gaussian', maxshape=None)
root['/entry/instrument/beam/profile'].attrs['type'] = 'NX_CHAR'
root['/entry/instrument/beam/profile'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/beam'].create_dataset(name='incident_polarisation_stokes', data='SAMPLE-CHAR-DATA', maxshape=None)
root['/entry/instrument/beam/incident_polarisation_stokes'].attrs['type'] = 'NX_CHAR'
root['/entry/instrument/beam/incident_polarisation_stokes'].attrs['EX_required'] = 'true'
 
root['/entry/source'].create_dataset(name='name', data='SAMPLE-CHAR-DATA', maxshape=None)
root['/entry/source/name'].attrs['type'] = 'NX_CHAR'
root['/entry/source/name'].attrs['EX_required'] = 'true'
 
root['/entry'].attrs['version'] = 'SAMPLE-CHAR-DATA'
root['/entry/instrument/name'].attrs['short_name'] = 'SAMPLE-CHAR-DATA'
root['/entry/instrument/detector/NXdetector_module/module_offset'].attrs['transformation_type'] = 'SAMPLE-CHAR-DATA'
root['/entry/instrument/detector/NXdetector_module/module_offset'].attrs['vector'] = '1.0'
root['/entry/instrument/detector/NXdetector_module/module_offset'].attrs['offset'] = '1.0'
root['/entry/instrument/detector/NXdetector_module/module_offset'].attrs['depends_on'] = 'SAMPLE-CHAR-DATA'
root['/entry/instrument/detector/NXdetector_module/fast_pixel_direction'].attrs['transformation_type'] = 'SAMPLE-CHAR-DATA'
root['/entry/instrument/detector/NXdetector_module/fast_pixel_direction'].attrs['vector'] = '1.0'
root['/entry/instrument/detector/NXdetector_module/fast_pixel_direction'].attrs['offset'] = '1.0'
root['/entry/instrument/detector/NXdetector_module/fast_pixel_direction'].attrs['depends_on'] = 'SAMPLE-CHAR-DATA'
root['/entry/instrument/detector/NXdetector_module/slow_pixel_direction'].attrs['transformation_type'] = 'SAMPLE-CHAR-DATA'
root['/entry/instrument/detector/NXdetector_module/slow_pixel_direction'].attrs['vector'] = '1.0'
root['/entry/instrument/detector/NXdetector_module/slow_pixel_direction'].attrs['offset'] = '1.0'
root['/entry/instrument/detector/NXdetector_module/slow_pixel_direction'].attrs['depends_on'] = 'SAMPLE-CHAR-DATA'
root['/entry/source/name'].attrs['short_name'] = 'SAMPLE-CHAR-DATA'
root['/'].attrs['default'] = 'entry'
root['/entry'].attrs['default'] = 'data'
root['/entry/data'].attrs['signal'] = 'data'
root['/entry/data/data'].attrs['signal'] = '1'
root.attrs['file_name'] = os.path.abspath('NXmx')
root.attrs['file_time'] = datetime.datetime.now().isoformat()
root.attrs['h5py_version'] = h5py.version.version
root.attrs['HDF5_Version'] = h5py.version.hdf5_version
root.close()


