 
import numpy as np
import datetime
import h5py
import os
 
# Note this example script was generated by nxdl_to_hdf5.py using the current 
# installed version of the NEXUS definitions ver[v2020.10] 
 
root = h5py.File('h5py_NXxlaueplate.h5', 'w')
 
root.create_group('entry')
root['/entry'].attrs['NX_class'] = 'NXentry'
root['/entry'].attrs['EX_required'] = 'true'
 
root['/entry/'].create_group('instrument')
root['/entry/instrument'].attrs['NX_class'] = 'NXinstrument'
root['/entry/instrument'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/'].create_group('detector')
root['/entry/instrument/detector'].attrs['NX_class'] = 'NXdetector'
root['/entry/instrument/detector'].attrs['EX_required'] = 'true'
 
# Valid enumeration values for root['/entry']['definition'] are: 
#	 NXxlaueplate
 
root['/entry'].create_dataset(name='definition', data='NXxlaueplate', maxshape=None)
root['/entry/definition'].attrs['type'] = 'NX_FLOAT'
root['/entry/definition'].attrs['EX_required'] = 'true'
 
root['/entry/instrument/detector'].create_dataset(name='diameter', data=1.0, maxshape=None)
root['/entry/instrument/detector/diameter'].attrs['type'] = 'NX_FLOAT'
root['/entry/instrument/detector/diameter'].attrs['EX_required'] = 'true'
root['/entry/instrument/detector/diameter'].attrs['units'] = 'NX_LENGTH'
root['/entry/definition'].attrs['EX_doc'] = '     Official NeXus NXDL schema to which this file conforms    '
root['/entry/instrument/detector/diameter'].attrs['EX_doc'] = '       The diameter of a cylindrical detector      '
root['/'].attrs['default'] = 'entry'
root.attrs['file_name'] = os.path.abspath('NXxlaueplate')
root.attrs['file_time'] = datetime.datetime.now().isoformat()
root.attrs['h5py_version'] = h5py.version.version
root.attrs['HDF5_Version'] = h5py.version.hdf5_version
root.close()


